version: '3.4'

services:
  basicscaffoldmonitoredwebapi:
    image: ${DOCKER_REGISTRY-}basicscaffoldmonitoredwebapi 
    ports:
    - 80:80 
    build:
      context: .
      dockerfile: BasicScaffoldMonitoredWebApi/Dockerfile

  prometheus_srv:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./BasicScaffoldMonitoredWebApi/Prometheus/prometheus_config.yml:/etc/prometheus/prometheus.yml 
    command:
    - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
    -  3000:3000

