global:
  scrape_interval: 10s

scrape_configs:
  -  job_name: 'aspnet_webapi_job'
     scrape_interval: 1s
     static_configs:
       -  targets: ['host.docker.internal']
     tls_config:
       insecure_skip_verify: true